import {
  describe,
  it,
  expect,
  beforeAll,
  afterAll,
  beforeEach,
  afterEach,
  vi,
} from "vitest";
import fc from "fast-check";
import { MongoMemoryServer } from "mongodb-memory-server";
import mongoose from "mongoose";
import { createShippingService } from "./shipping.service.js";
import Order from "../../modules/orders/order.model.js";

// Feature: planet-of-toys-ecommerce, Property 21: Successful Shiprocket
// fulfilment transitions to CREATED — for any successful courier-assignment and
// AWB-generation result, the order stores the returned AWB and courier details
// and sets shipmentStatus == CREATED. Validates Requirements 11.3, 17.5.
//
// Convention mirrors shipping.service.test.js: an in-memory MongoDB backs the
// Order model (getCredential falls back to env vars since no settings document
// is created) and the Shiprocket HTTP client is always mocked, so no real
// network call is made. Here the mock returns SUCCESS with varied
// awb/courier/shipment_id/order_id values generated by fast-check.

const TEST_EMAIL = "ops@planetoftoys.test";
const TEST_PASSWORD = "shiprocket-secret-DO-NOT-LEAK";
const PICKUP = "110001";

let mongod;
const savedEnv = {};

beforeAll(async () => {
  mongod = await MongoMemoryServer.create();
  await mongoose.connect(mongod.getUri());
});

afterAll(async () => {
  await mongoose.disconnect();
  if (mongod) await mongod.stop();
});

beforeEach(() => {
  for (const k of [
    "ENCRYPTION_KEY",
    "SHIPROCKET_EMAIL",
    "SHIPROCKET_PASSWORD",
    "SHIPROCKET_PICKUP_PINCODE",
  ]) {
    savedEnv[k] = process.env[k];
  }
  process.env.ENCRYPTION_KEY = "shipping-test-encryption-key";
  process.env.SHIPROCKET_EMAIL = TEST_EMAIL;
  process.env.SHIPROCKET_PASSWORD = TEST_PASSWORD;
  process.env.SHIPROCKET_PICKUP_PINCODE = PICKUP;
});

afterEach(async () => {
  for (const [k, v] of Object.entries(savedEnv)) {
    if (v === undefined) delete process.env[k];
    else process.env[k] = v;
  }
  vi.restoreAllMocks();
  await Order.deleteMany({});
});

/**
 * Build a mock HTTP client whose create-order and AWB-assignment responses
 * are a SUCCESSFUL Shiprocket flow carrying the supplied identifiers. The AWB
 * result is nested under response.data exactly as the real provider returns it,
 * matching the shape the service unwraps.
 */
function mockSuccessClient({ awb, courier, shipmentId, srOrderId }) {
  let authCount = 0;
  const request = vi.fn(async (opts) => {
    if (opts.url.endsWith("/auth/login")) {
      authCount += 1;
      return { status: 200, data: { token: `token-${authCount}` } };
    }
    if (opts.url.endsWith("/orders/create/adhoc")) {
      return { status: 200, data: { order_id: srOrderId, shipment_id: shipmentId } };
    }
    if (opts.url.endsWith("/courier/assign/awb")) {
      return {
        status: 200,
        data: {
          awb_assign_status: 1,
          response: { data: { awb_code: awb, courier_name: courier } },
        },
      };
    }
    return { status: 404, data: null };
  });
  return { request };
}

/** Persist a minimal valid PENDING order, mirroring shipping.service.test.js. */
async function seedOrder() {
  return Order.create({
    orderId: `POT-240101-${Math.floor(Math.random() * 9000 + 1000)}`,
    customer: {
      name: "Asha Verma",
      phone: "9876543210",
      email: "asha@example.test",
      address: "12 MG Road",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560001",
    },
    items: [
      {
        productId: new mongoose.Types.ObjectId(),
        name: "Toy Robot",
        quantity: 2,
        unitPrice: 499,
      },
    ],
    amount: 998,
    paymentMethod: "ONLINE",
    paymentStatus: "PAID",
  });
}

describe("Property 21: successful Shiprocket fulfilment transitions to CREATED (Req 11.3, 17.5)", () => {
  it("stores the returned AWB/courier/SR order id and sets shipmentStatus=CREATED for any successful result", async () => {
    await fc.assert(
      fc.asyncProperty(
        // Varied, non-empty AWB and courier identifiers, plus distinct numeric
        // shipment_id and order_id values, spanning the realistic input space.
        fc.string({ minLength: 1, maxLength: 24 }).filter((s) => s.trim().length > 0),
        fc.string({ minLength: 1, maxLength: 24 }).filter((s) => s.trim().length > 0),
        fc.integer({ min: 1, max: 9_999_999 }),
        fc.integer({ min: 1, max: 9_999_999 }),
        async (awb, courier, shipmentId, srOrderId) => {
          const http = mockSuccessClient({ awb, courier, shipmentId, srOrderId });
          const service = createShippingService({ httpClient: http });
          const order = await seedOrder();

          const result = await service.createShipment(order);

          // The returned result reports CREATED and carries the SR identifiers.
          expect(result.ok).toBe(true);
          expect(result.shipmentStatus).toBe("CREATED");
          expect(result.awb).toBe(awb);
          expect(result.courier).toBe(courier);
          expect(result.shiprocketOrderId).toBe(String(srOrderId));

          // The persisted order stores AWB/courier/SR order id and is CREATED.
          const persisted = await Order.findById(order._id).lean();
          expect(persisted.shipmentStatus).toBe("CREATED");
          expect(persisted.shipping.awb).toBe(awb);
          expect(persisted.shipping.courier).toBe(courier);
          expect(persisted.shipping.shiprocketOrderId).toBe(String(srOrderId));

          await Order.deleteMany({});
        }
      ),
      { numRuns: 100 }
    );
  });
});
